### ISSUE TITLE
Find way of updating caskroom tap

### ISSUE THREAD

**Issue by dgreene-r7** [davepgreene/brew-cask-tools#1]
https://github.com/davepgreene/brew-cask-tools/blob/master/lib/bct/tasks.rb#L16 is clearly not working. There has to be a way of updating taps short of running `git pull` from the caskroom tap directory.

**Comment by davepgreene** [comment]
Fixed in 4ade192 but it would be nice if Homebrew allowed another way of specifically targeting taps for update.
